name = "REPL"
defaultTargets = ["repl"]

[[lean_lib]]
name = "REPL"

[[lean_exe]]
name = "repl"
root = "REPL.Main"
supportInterpreter = true

[[lean_exe]]
name = "test"
root = "Test"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0-rc1"

[[lean_exe]]
name = "dump_ast"
root = "dump_ast"
supportInterpreter = true